name: Publish on Itch.IO  🎮
on: [workflow_call, workflow_dispatch]

jobs:
  itchio-deploy:
      name: Deploy to Itch.IO  🎮
      runs-on: ubuntu-lateste
      steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - uses: actions/download-artifact@v3
         with:
           name: build-ItchIO
           path: build

       - name: Display structure of root files
         run: ls -R
         working-directory: build/WebGL

        - uses: manleydev/butler-publish-itchio-action@v1.0.3
          env:
            BUTLER_CREDENTIALS: ${{ secrets.ITCHIO_KEY }}
            CHANNEL: HTML
            ITCH_GAME: kurzgesagt
            ITCH_USER: spark8
            PACKAGE: build/WebGL
