@startuml

!define RECTANGLE class
!define INTERFACE interface

INTERFACE IStage {
    +EnterStageAsync(CancellationToken)
    +UpdateStageAsync(CancellationToken)
    +ExitStageAsync(CancellationToken)
}

RECTANGLE PlayerStageController {
    -IStage currentStage
    +Awake()
    +OnTriggerEnter(Collider)
    +OnTriggerExit(Collider)
    +Update()
}

RECTANGLE BaseStage {
    -List<StageStep> Steps
    +Awake()
    +EnterStageAsync(CancellationToken)
    +UpdateStageAsync(CancellationToken)
    +ExitStageAsync(CancellationToken)
}

RECTANGLE GreenStage {
    +Awake()
    +EnterStageAsync(CancellationToken)
    +UpdateStageAsync(CancellationToken)
    +ExitStageAsync(CancellationToken)
}

PlayerStageController --> IStage: Inject
BaseStage ..|> IStage: Implements
GreenStage --|> BaseStage: Inherits

@enduml

