name: 1. Acquire Activation File 🔑
on: workflow_dispatch

jobs:
    AcquireActivationFile:
        name: Acquire Activation File
        runs-on: ubuntu-latest
        steps:
            # Request manual activation file
            - name: Request manual activation file
              id: getManualLicenseFile
              uses: game-ci/unity-request-activation-file@v2
            # Upload artifact (Unity_v20XX.X.XXXX.alf)
            - name: Expose as artifact
              uses: actions/upload-artifact@v3
              with:
                  name: ${{ steps.getManualLicenseFile.outputs.filePath }}
                  path: my-artifacts
                  retention-days: 90

            - name: Rename artifact
              run: |
                # Generate a timestamp in the format "YYYY-MM-DD_HH-MM-SS"
                timestamp=$(date "+%Y-%m-%d_%H-%M-%S")
                mv ${{ steps.getManualLicenseFile.outputs.filePath }} ${{ steps.getManualLicenseFile.outputs.filePath }}_$timestamp.zip                  
