name: Game-CI Unity Build 🎮
on:
  workflow_call:
    inputs:
      BUILD_TARGET:
        description: 'Unity build target platform'
        default: Android
        required: true
        type: string

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  ARTIFACT_NAME: ${{ github.event.repository.name }} #-$(date +%Y%m%d%H%M)"
  UNITY_VERSION: 2021.4.10f1

jobs:
  build:
    name: Building for ${{ inputs.BUILD_TARGET }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
  
      - name: cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ inputs.BUILD_TARGET }}
          restore-keys: Library-
    
      - name: Unity Build using Game CI
        uses: game-ci/unity-builder@v2.1.2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
         # email and pwd only required for pro license
         # UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
         # UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ inputs.BUILD_TARGET }}
          allowDirtyBuild: true
          #versioning: Semantic
          #unityVersion: ${{ env.UNITY_VERSION }}
  
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ inputs.BUILD_TARGET }}-${{ env.ARTIFACT_NAME }}"
          path: ${{ env.ARTIFACT_PATH }}

      - name: Echo URL
        run: echo "https://github.com/$GITHUB_REPOSITORY/actions/downloads/${{ env.BUILD_NAME }}"