name: Build Unity 🎮

env:
    ARTIFACT_PATH: build
    ARTIFACT_NAME: ${{ github.event.repository.name }} #-$(date +%Y%m%d%H%M)"
    UNITY_VERSION: 2021.4.10f1 #2020.1.14f1 # recommended version for Ubuntu 20.04 LTS
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    BUILD_NUMBER: 1 #$(date +%s)
    UNITY_INSTALL_DIR: /opt/unity

on:
  workflow_call:
    inputs:
      BUILD_TARGET:
        description: 'Unity build target platform'
        default: Android
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Test input Target Platform
      run: echo BUILD_TARGET ${{ inputs.BUILD_TARGET }}

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true

    - name: cache
      uses: actions/cache@v3
      with:
        path: Library
        key: Library-${{ inputs.BUILD_TARGET }}
        restore-keys: Library-

    - uses: webbertakken/unity-builder@v2
      with:
        targetPlatform: ${{ inputs.BUILD_TARGET }}
        allowDirtyBuild: true

    # - name: Unity Build using Game CI
    #   uses: game-ci/unity-builder@v2.1.2
    #   env:
    #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    #     # email and pwd only required for pro license
    #     # UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    #     # UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    #   with:
    #     targetPlatform: ${{ inputs.BUILD_TARGET }}
    #     unityVersion: ${{ env.UNITY_VERSION }}
    #     versioning: Semantic
    #     allowDirtyBuild: true
    #     install-location: /opt/Unity
    #     # androidAppBundle: true
    #     # androidKeystoreName: user.keystore
    #     # androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
    #     # androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
    #     # androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
    #     # androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}

    #unnecessary as it's already included in ubuntu
    # - name: Install Unity and move
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get -y install unity=${{ env.UNITY_VERSION }}
    #     cd /var/cache/apt/archives/
    #     sudo dpkg -i --root=${{ env.UNITY_INSTALL_DIR }} unity*.deb

    # - name: Install Unity simple
    #   run: sudo Unity-Editor-${{ env.UNITY_VERSION }} -batchmode -install ${{ env.UNITY_INSTALL_DIR }}
        

    # - name: Find Unity directory
    #   run: echo "Unity directories $(find /opt/ -type d -name "*unity*" -print 2>/dev/null)"

#try remove the /Editor/Unity
    # - name: Native Unity build Simple for ${{ env.BUILD_TARGET }}
    #   run: ${{ env.UNITY_INSTALL_DIR }}/Editor/Unity \ 
    #        -batchmode \
    #        -nographics \
    #        -projectPath $(pwd) \
    #        -buildTarget ${{ env.BUILD_TARGET }} \
    #        -buildName ${{ env.BUILD_NAME }} \
    #        -quit

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: "${{ inputs.BUILD_TARGET }}-${{ env.ARTIFACT_NAME }}"
        path: ${{ env.ARTIFACT_PATH }}

    - name: Echo URL
      run: echo "https://github.com/$GITHUB_REPOSITORY/actions/downloads/${{ env.BUILD_NAME }}"
