name: Game-CI Unity Build 🎮
on:
  workflow_call:
    inputs:
      BUILD_TARGET:
        description: 'Unity build target platform'
        default: Android
        required: true
        type: string

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_VERSION: 2021.4.10f1
  DUMMY_BUILD: true

jobs:
  build:
    name: Building for ${{ inputs.BUILD_TARGET }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Fetch
        run: git fetch --prune --unshallow
  
      - name: cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ inputs.BUILD_TARGET }}
          restore-keys: Library-

      - name: Check DUMMY_BUILD
        run: |
          if [ "$DUMMY_BUILD" == "true" ]; then
            echo "::set-env name=NEXT_STEP::dummyArtifact"
          else
            echo "::set-env name=NEXT_STEP::actualBuild"
          fi
      - name: ${{ env.NEXT_STEP }}
        run: echo "Running ${{ env.NEXT_STEP }}"


      - name: Generate dummy artifact
        if: env.NEXT_STEP == 'dummyArtifact'
        run: echo "Hello, World!" > ${{ env.ARTIFACT_FILE }}

      - name: Unity Build using Game CI
        if: env.NEXT_STEP == 'actualBuild'
        uses: game-ci/unity-builder@v2.1.2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
         # email and pwd only required for pro license
         # UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
         # UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ inputs.BUILD_TARGET }}
          allowDirtyBuild: true
          versioning: Semantic
          #unityVersion: ${{ env.UNITY_VERSION }}
  
      - name: Generate dummy artifact
        run: echo "Hello, World!" > ${{ env.ARTIFACT_FILE }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ github.event.repository.name }}-${{ inputs.BUILD_TARGET }}-$(date +%Y%m%d%H%M)"
          path: build

      - name: Echo URL
        run: echo "https://github.com/$GITHUB_REPOSITORY/actions/downloads/${{ env.BUILD_NAME }}"
    
    # teams notification
      - name: Set artifact URL
        id: set-artifact-url
        run: echo "artifacturl=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT
      - name: Test artifact URL
        run: echo "The artifact URL is ${{ steps.set-artifact-url.outputs.artifacturl }}"
      
    outputs:
      artifacturl: ${{ steps.set-artifact-url.outputs.artifacturl }}
  
  notify-teams:
    needs: build
    uses: ./.github/workflows/ms-teams-notification.yml
    secrets: inherit
    with:
      artifact_url: ${{ needs.build.outputs.artifacturl }}