name: Windows Build 🖥️
on: [workflow_call, workflow_dispatch]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  WindowsBuild:
    name: Windows Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
  
      - name: cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-StandaloneWindows64
          restore-keys: Library-
    
      - uses: webbertakken/unity-builder@v2
        with:
          targetPlatform: StandaloneWindows64
          allowDirtyBuild: true
  
      - uses: actions/upload-artifact@v3
        with:
          name: build-StandaloneWindows64
          path: build/StandaloneWindows64
