name: Deploy to Github Pages 🚀

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:    
      - main
      #- 'releases/**'
 

jobs:
  deployPages:
      name: Deploy to Github Pages 🚀 🕸 
      runs-on: ubuntu-latest
      steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - uses: actions/download-artifact@v3
         with:
           name: build-WebGL
           path: build

       - name: Display structure of root files
         run: ls -R
         working-directory: build/WebGL

       - name: Deploy 🚀
         uses: JamesIves/github-pages-deploy-action@4.1.4
         with:
           branch: gh-pages
           folder: build/WebGL



       - name: Download artifacts
       - uses: dawidd6/action-download-artifact@v2.24.0
         with:
          workflow: deploy-to-webgl.yml
          workflow_conclusion: success   
          path:  ${{ env.WEB_DIR }}


