name: Deploy to Github Pages 🚀
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:    
      - main
      - 'releases/**'

env: 
  WEB_DIR: build/WebGL

jobs:
  deployPages:
      name: Deploy to Github Pages 🚀 🕸 
      runs-on: ubuntu-latest
      steps:
       - name: Checkout 
         uses: actions/checkout@v3

      # This would only work if the artifact was produced within the same workflow or on workflow_call
      #  - name: Download artifacts      
      #  - uses: actions/download-artifact@v3
      #    with:
      #      name: build-WebGL
      #      path: ${{ env.WEB_DIR }}

       - name: Download artifacts
       - uses: dawidd6/action-download-artifact@v2.24.0
         with:
          workflow: deploy-to-webgl.yml
          workflow_conclusion: success   
          path:  ${{ env.WEB_DIR }}

       - name: Test download
         run: ls -R
         working-directory: ${{ env.WEB_DIR }}

       - name: Deploy 🚀
         uses: JamesIves/github-pages-deploy-action@4.1.4
         with:
           branch: gh-pages
           folder: ${{ env.WEB_DIR }}
