env:
  BUILD_TARGET: Android
  #BUILD_NUMBER: $(date +%s)
  ARTIFACT_PATH: build
  ARTIFACT_NAME: "${{ GITHUB.REPOSITORY }}-${{ BUILD_TARGET }}-$(date +%Y%m%d%H%M)"
  UNITY_VERSION: 2021.3.16f1

name: Build Android 2

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true
    - name: cache
      uses: actions/cache@v3
      with:
        path: Library
        key: Library-${{ BUILD_TARGET }}
        restore-keys: Library-

    - name: Unity Build
      uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        # email and pwd only required for pro license
        # UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        # UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: ${{ env.BUILD_TARGET }}
        version: ${{ env.UNITY_VERSION }}
        install-location: /opt/Unity
        versioning: Semantic
        allowDirtyBuild: true
        # androidAppBundle: true
        # androidKeystoreName: user.keystore
        # androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        # androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
        # androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
        # androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}

    # - name: Build Android
    #   run: /opt/Unity/Editor/Unity -batchmode -nographics -logFile /dev/stdout -projectPath . 
    #        -executeMethod UnityEditor.Android.AndroidBuildCommand.BuildPlayer 
    #        -buildTarget ${{ env.BUILD_TARGET }} 
    #        -buildName ${{ env.BUILD_NAME }} 
    #        -buildNumber ${{ env.BUILD_NUMBER }} 
    #        -quit

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: "${{ env.ARTIFACT_PATH }}/${{ env.BUILD_TARGET }}"

    - name: Echo URL
      run: echo "https://github.com/$GITHUB_REPOSITORY/actions/downloads/${{ env.BUILD_NAME }}"
