name: Publish on Itch.IO - KikimoraGames 🎮
on: [workflow_call, workflow_dispatch]

env:
  ITCH_USERNAME: spark8
  ITCH_GAME_ID: kurzgesagt
jobs:
  deploy:
    name: Upload to Itch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        channel:
          #- windows
          - webgl
    steps:
      - uses: actions/download-artifact@v2.0.8
        with:
          name: build-WebGL
          path: build/WebGL
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.ITCHIO_KEY}}
          gameData: ./build/${{ matrix.template }}
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
          buildNumber: ${{ needs.version.outputs.version_hash }}


          
      
