name: Publish on Itch.IO - josephbmanley extended - windows 🎮
on: [workflow_call, workflow_dispatch]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  ITCH_USER_NAME: spark8
  ITCH_GAME_NAME: kurzgesagt
  CHANNEL: windows #linux,osx
  ITCH_KEY: ${{ secrets.ITCHIO_KEY }}
  TAGVERSION: 1
  PROJECT_PATH: build/StandaloneWindows64

jobs:
  build-windows:
    name: Build Windows
    uses: Muammar81/GitActions-Test/.github/workflows/deploy-to-windows64.yml@main
    secrets: inherit
    
  publish:
    needs: build-windows
    runs-on: ubuntu-20.04
    steps:
    - name: Publish Windows build to itch.io
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ env.ITCH_KEY }}
        CHANNEL: ${{ env.CHANNEL }}
        ITCH_USER: ${{ env.ITCH_USER_NAME }}
        ITCH_GAME: ${{ env.ITCH_GAME_NAME }}
        PACKAGE: ${{ env.PROJECT_PATH }}
        VERSION: ${{ env.TAGVERSION }}
