name: Build for Windows 🖥️
on: [workflow_call, workflow_dispatch]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildWindows:
    name: Build for Windows 🖥️
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@latest
  
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
  
      - name: Restore LFS cache
        uses: actions/cache@latest
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
  
      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard
  
      - name: Restore Library cache
        uses: actions/cache@latest
        with:
          path: Library
          key: Library-build-StandaloneWindows64
          restore-keys: |
            Library-build-
            Library-
  
      - uses: webbertakken/unity-builder@latest
        with:
          targetPlatform: StandaloneWindows64
  
      - uses: actions/upload-artifact@latest
        with:
          name: build-StandaloneWindows64
          path: build/StandaloneWindows64
