name: Generate UML Diagrams

on:
  push:
    branches:
      - stateless-system
  workflow_dispatch:

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PlantUML Dependencies
      run: sudo apt-get update && sudo apt-get install -y graphviz

    - name: Install PlantUML
      run: sudo apt-get install -y plantuml

    - name: Generate Diagrams
      run: plantuml *.puml

    - name: Commit and Push Diagrams
      run: |
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "${{ github.actor }}"
        git add -A
        git commit -m "Generate UML diagrams" || echo "No changes to commit"
        git push origin || echo "No changes to push"