name: Hello Variables

on:
  workflow_dispatch

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello to Actions Path"
        run: echo "RUNNER_OS $env:RUNNER_OS ${{ env.RUNNER_OS }}"
          echo "GITHUB_ACTION_PATH $env:GITHUB_ACTION_PATH ${{ env.GITHUB_ACTION_PATH }}"
          echo "GITHUB_ACTOR $env:GITHUB_ACTOR ${{ env.GITHUB_ACTOR }}"
          echo "github.repository ${{ github.repository }}"
        
