name: Hello Variables

on:
  workflow_dispatch

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
      repo: ${{ github.repository }}
    steps:
      - name: "env:repo"
        run: echo "Repo path $env:repo"
        
