name: Hello Variables

on:
  workflow_dispatch

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello to Actions Path"
        run: echo "$env:RUNNER_OS ${{ env.action_state }}"
